apiVersion: v1
kind: Namespace
metadata:
  name: katacore
  labels:
    name: katacore
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: katacore-monitoring
  labels:
    name: katacore-monitoring
    env: production
